# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
        files: \.(TcPOU|TcDUT|TcGVL)$
-   repo: https://github.com/pcdshub/pre-commit-hooks.git
    rev: v1.0.0
    hooks:
    -   id: twincat-leading-tabs-remover
    -   id: twincat-lineids-remover
    -   id: twincat-xmllint-format
