- id: twincat-lineids-remover
  name: twincat lineids
  description: Eliminate TwinCAT line ID lines
  entry: twincat-lineids-remover
  language: python
  files: .*\.TcPOU$
- id: leading-tabs-remover
  name: leading tabs remover
  description: Replace leading tabs with 4 spaces
  entry: leading-tabs-remover
  language: python
- id: twincat-leading-tabs-remover
  name: twincat leading tabs remover
  description: leading-tabs-remover configured for TwinCAT
  entry: leading-tabs-remover
  language: python
  files: .*\.(TcPOU|TcDUT|TcGVL)$
- id: xmllint-format
  name: xmllint formatter
  description: Use xmllint --format to beautify xml files
  entry: xmllint-format
  language: python
  types: [xml]
- id: twincat-xmllint-format
  name: twincat xml formatter
  description: xmllint-format configured for TwinCAT
  entry: xmllint-format
  language: python
  files: .*\.(tmc|tpy|xml)$
