- id: twincat-lineids-remover
  name: TwinCAT LineID Remover
  description: Eliminate TwinCAT line ID lines
  entry: twincat-lineids-remover
  language: python
  files: .*\.TcPOU$
- id: leading-tabs-remover
  name: Leading Tabs Remover
  description: Replace leading tabs with 4 spaces
  entry: leading-tabs-remover
  language: python
- id: twincat-leading-tabs-remover
  name: TwinCAT Leading Tabs Remover
  description: leading-tabs-remover configured for TwinCAT
  entry: leading-tabs-remover
  language: python
  files: .*\.(TcPOU|TcDUT|TcGVL)$
- id: xml-format
  name: XML Formatter
  description: Use lxml to beautify xml files
  entry: xml-format
  language: python
  types: [xml]
- id: twincat-xml-format
  name: TwinCAT XML Formatter
  description: xml-format configured for TwinCAT
  entry: xml-format
  language: python
  files: .*\.(tmc|tpy|xml)$
- id: check-fixed-library-versions
  name: Check fixed library versions
  description: Checks if there are PLC libraries whos versions are not fixed.
  entry: check-fixed-library-versions
  language: python
  files: .*\.plcproj$
- id: pytmc-pragma-linter
  name: pytmc-pragma-linter
  description: Lint pytmc pragmas
  entry: bash -c 'set -ex; for fn in "$@"; do pytmc pragmalint "$fn"; done' --
  language: python
  files: .*\.(TcPOU|TcGVL|TcDUT)$
  additional_dependencies: ["pytmc"]
