- id: twincat-lineids-remover
  name: twincat lineids
  description: Eliminate TwinCAT line ID lines
  entry: twincat-lineids-remover
  language: python
  files: .*\.TcPOU$
- id: leading-tabs-remover
  name: leading tabs remover
  description: Replace leading tabs with 4 spaces
  entry: leading-tabs-remover
  language: python
- id: twincat-leading-tabs-remover
  name: twincat leading tabs remover
  description: leading-tabs-remover configured for TwinCAT
  entry: leading-tabs-remover
  language: python
  files: .*\.(TcPOU|TcDUT|TcGVL)$
- id: xml-format
  name: xml format
  description: Use lxml to beautify xml files
  entry: xml-format
  language: python
  types: [xml]
- id: twincat-xml-format
  name: twincat xml format
  description: xml-format configured for TwinCAT
  entry: xml-format
  language: python
  files: .*\.(tmc|tpy|xml)$
